docuseal_src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  if !Docuseal.multitenant? && defined?(Sidekiq::Web)
    authenticated :user, ->(u) { u.sidekiq? } do
      mount Sidekiq::Web => '/jobs'
    end
  end

  root 'dashboard#index'

  get 'up' => 'rails/health#show'

  devise_for :users,
             path: '/', only: %i[sessions passwords omniauth_callbacks],
             controllers: begin
               options = { sessions: 'sessions', passwords: 'passwords' }
               options[:omniauth_callbacks] = 'omniauth_callbacks' if User.devise_modules.include?(:omniauthable)
               options
             end

  devise_scope :user do
    resource :invitation, only: %i[update] do
      get '' => :edit
    end
  end

  namespace :api, defaults: { format: :json } do
    resource :user, only: %i[show]
    resources :attachments, only: %i[create]
    resources :submitter_email_clicks, only: %i[create]
    resources :submitter_form_views, only: %i[create]
    resources :submitters, only: %i[index show update]
    resources :submissions, only: %i[index show create destroy] do
      resources :documents, only: %i[index], controller: 'submission_documents'
      collection do
        resources :init, only: %i[create], controller: 'submissions'
        resources :emails, only: %i[create], controller: 'submissions', as: :submissions_emails
      end
    end
    resources :templates, only: %i[create update show index destroy] do
      resources :clone, only: %i[create], controller: 'templates_clone'
      resources :submissions, only: %i[index create]
    end
    resources :tools, only: %i[] do
      post :merge, on: :collection
      post :verify, on: :collection
    end
    scope 'events' do
      resources :form_events, only: %i[index], path: 'form/:type'
      resources :submission_events, only: %i[index], path: 'submission/:type'
    end
  end

  resources :verify_pdf_signature, only: %i[create]
  resource :mfa_setup, only: %i[show new edit create destroy], controller: 'mfa_setup'
  resources :account_configs, only: %i[create]
  resources :user_configs, only: %i[create]
  resources :encrypted_user_configs, only: %i[destroy]
  resources :timestamp_server, only: %i[create]
  resources :dashboard, only: %i[index]
  resources :setup, only: %i[index create]
  resource :newsletter, only: %i[show update]
  resources :enquiries, only: %i[create]
  resources :users, only: %i[new create edit update destroy]
  resource :user_signature, only: %i[edit update destroy]
  resource :user_initials, only: %i[edit update destroy]
  resources :submissions_archived, only: %i[index], path: 'submissions/archived'
  resources :submissions, only: %i[index], controller: 'submissions_dashboard'
  resources :submissions, only: %i[show destroy] do
    resources :unarchive, only: %i[create], controller: 'submissions_unarchive'
  end
  resources :submitters, only: %i[edit update]
  resources :console_redirect, only: %i[index]
  resources :upgrade, only: %i[index], controller: 'console_redirect'
  resources :manage, only: %i[index], controller: 'console_redirect'
  resource :testing_account, only: %i[show destroy]
  resources :testing_api_settings, only: %i[index]
  resources :submitters_autocomplete, only: %i[index]
  resources :template_folders_autocomplete, only: %i[index]
  resources :webhook_secret, only: %i[show update]
  resources :webhook_preferences, only: %i[update]
  resource :templates_upload, only: %i[create]
  # authenticated do
  #   resource :templates_upload, only: %i[show], path: 'new'
  # end
  resource :templates_upload, only: %i[show], path: 'new'
  resources :templates_archived, only: %i[index], path: 'templates/archived'
  resources :folders, only: %i[show edit update destroy], controller: 'template_folders'
  resources :template_sharings_testing, only: %i[create]
  resources :templates, only: %i[index], controller: 'templates_dashboard'
  resources :templates, only: %i[new create edit update show destroy] do
    resource :debug, only: %i[show], controller: 'templates_debug' if Rails.env.development?
    resources :documents, only: %i[create], controller: 'template_documents'
    resources :restore, only: %i[create], controller: 'templates_restore'
    resources :archived, only: %i[index], controller: 'templates_archived_submissions'
    resources :submissions, only: %i[new create]
    resource :folder, only: %i[edit update], controller: 'templates_folders'
    resource :preview, only: %i[show], controller: 'templates_preview'
    resource :form, only: %i[show], controller: 'templates_form_preview'
    resource :code_modal, only: %i[show], controller: 'templates_code_modal'
    resource :preferences, only: %i[show create], controller: 'templates_preferences'
    resources :recipients, only: %i[create], controller: 'templates_recipients'
    resources :submissions_export, only: %i[index new]
  end
  resources :preview_document_page, only: %i[show], path: '/preview/:signed_uuid'
  resource :blobs_proxy, only: %i[show], path: '/file/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'
  resource :blobs_proxy, only: %i[show], path: '/blobs_proxy/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'

  if Docuseal.multitenant?
    resource :blobs_proxy_legacy, only: %i[show],
                                  path: '/blobs/proxy/:signed_id/*filename',
                                  controller: 'api/active_storage_blobs_proxy_legacy',
                                  as: :rails_blob
    get '/disk/:encoded_key/*filename' => 'active_storage/disk#show', as: :rails_disk_service
    put '/disk/:encoded_token' => 'active_storage/disk#update', as: :update_rails_disk_service
    post '/direct_uploads' => 'active_storage/direct_uploads#create', as: :rails_direct_uploads
  end

  resources :start_form, only: %i[show update], path: 'd', param: 'slug' do
    get :completed
  end

  resources :submit_form, only: %i[], path: '' do
    get :success, on: :collection
  end

  resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
    resources :values, only: %i[index], controller: 'submit_form_values'
    resources :download, only: %i[index], controller: 'submit_form_download'
    resources :decline, only: %i[create], controller: 'submit_form_decline'
    resources :invite, only: %i[create], controller: 'submit_form_invite'
    get :completed
  end

  resources :submit_form_draw_signature, only: %i[show], path: 'p', param: 'slug'

  resources :submissions_preview, only: %i[show], path: 'e', param: 'slug' do
    get :completed
  end

  resources :send_submission_email, only: %i[create] do
    get :success, on: :collection
  end

  resources :submitters, only: %i[], param: 'slug' do
    resources :download, only: %i[index], controller: 'submissions_download'
    resources :send_email, only: %i[create], controller: 'submitters_send_email'
    resources :debug, only: %i[index], controller: 'submissions_debug' if Rails.env.development?
  end

  scope '/settings', as: :settings do
    unless Docuseal.multitenant?
      resources :storage, only: %i[index create], controller: 'storage_settings'
      resources :sms, only: %i[index], controller: 'sms_settings'
    end
    resources :email, only: %i[index create], controller: 'email_smtp_settings'
    resources :sso, only: %i[index], controller: 'sso_settings'
    resources :notifications, only: %i[index create], controller: 'notifications_settings'
    resource :esign, only: %i[show create new update destroy], controller: 'esign_settings'
    resources :users, only: %i[index]
    resources :archived_users, only: %i[index], path: 'users/:status', controller: 'users',
                               defaults: { status: :archived }
    resources :integration_users, only: %i[index], path: 'users/:status', controller: 'users',
                                  defaults: { status: :integration }
    resource :personalization, only: %i[show create], controller: 'personalization_settings'
    resources :api, only: %i[index create], controller: 'api_settings'
    resource :webhooks, only: %i[show create update], controller: 'webhook_settings'
    resource :account, only: %i[show update destroy]
    resources :profile, only: %i[index] do
      collection do
        patch :update_contact
        patch :update_password
        patch :update_app_url
      end
    end
  end

  get '/js/:filename', to: 'embed_scripts#show', as: :embed_script

  ActiveSupport.run_load_hooks(:routes, self)
end

docuseal_src/app/views/templates/_dropzone.html.erb
<%= form_for '', url: templates_upload_path, id: form_id = SecureRandom.uuid, method: :post, class: 'mt-8 block', html: { enctype: 'multipart/form-data' } do %>
  <input type="hidden" name="form_id" value="<%= form_id %>">
  <button type="submit" class="hidden"></button>
  <file-dropzone data-submit-on-upload="true" class="w-full">
    <label for="file_dropzone_input" class="w-full block h-52 relative hover:bg-base-200/30 rounded-xl border border-2 border-base-300 border-dashed">
      <div class="absolute top-0 right-0 left-0 bottom-0 flex items-center justify-center p-2">
        <div class="flex flex-col items-center text-center">
          <span data-target="file-dropzone.icon" class="flex flex-col items-center">
            <span>
              <%= svg_icon('cloud_upload', class: 'w-10 h-10') %>
            </span>
            <div class="font-medium mb-1">
              <%= t('upload_new_document') %>
            </div>
            <div class="text-xs">
              <%= t('click_to_upload_or_drag_and_drop_html') %>
            </div>
          </span>
          <span data-target="file-dropzone.loading" class="flex flex-col items-center hidden">
            <%= svg_icon('loader', class: 'w-10 h-10 animate-spin') %>
            <div class="font-medium mb-1">
              <%= t('uploading') %>...
            </div>
          </span>
        </div>
        <input id="file_dropzone_input" name="files[]" class="hidden" data-action="change:file-dropzone#onSelectFiles" data-target="file-dropzone.input" type="file" accept="image/*, application/pdf<%= ', .docx, .doc, .xlsx, .xls, .odt, .rtf' if Docuseal.multitenant? %>" multiple>
      </div>
    </label>
  </file-dropzone>
<% end %>

docuseal_src/app/views/templates/_template.html.erb
<div class="h-36 relative group">
  <a href="<%= template_path(template) %>" class="flex h-full flex-col justify-between rounded-2xl pt-6 px-7 w-full bg-base-200 peer">
    <div class="pb-4 text-xl font-semibold" style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2;">
      <% template.name.split(/(_)/).each do |item| %><%= item %><wbr><% end %>
    </div>
    <div class="pb-6 pt-1 space-y-1">
      <p class="flex items-center space-x-1 text-xs text-base-content/60">
        <%= svg_icon('user', class: 'w-4 h-4') %>
        <span><%= template.author.full_name.presence || template.author.email.to_s.sub(/\+\w+@/, '@') %></span>
        <% if template.account_id != current_account.id %>
          <span class="badge badge-neutral badge-outline badge-sm text-[10px] uppercase"><%= t('shared') %></span>
        <% end %>
      </p>
      <p class="flex text-xs text-base-content/60">
        <span class="flex items-center space-x-1 w-1/2">
          <%= svg_icon('calendar', class: 'w-4 h-4') %>
          <span><%= l(template.created_at.in_time_zone(current_account.timezone), format: :short, locale: current_account.locale) %></span>
        </span>
        <% if template.archived_at? %>
          <span class="flex items-center space-x-1 w-1/2">
            <%= svg_icon('folder', class: 'w-4 h-4 flex-shrink-0') %>
            <span class="truncate"><%= template.folder.name %></span>
          </span>
        <% end %>
      </p>
    </div>
  </a>
  <div class="absolute top-0 bottom-0 w-0 flex items-center hidden md:group-hover:flex" style="right: 37px">
    <div class="space-y-1">
      <% if can?(:update, template) && !template.archived_at? && template.account_id == current_account.id %>
        <span class="tooltip tooltip-left" data-tip="<%= t('move') %>">
          <a href="<%= edit_template_folder_path(template.id) %>" data-turbo-frame="modal" class="btn btn-xs hover:btn-outline bg-base-200 btn-circle">
            <%= svg_icon('folder_share', class: 'w-4 h-4') %>
          </a>
        </span>
      <% end %>
      <% if template.archived_at? && can?(:update, template) %>
        <span class="tooltip tooltip-left" data-tip="<%= t('restore') %>">
          <%= button_to template_restore_index_path(template), class: 'btn btn-xs hover:btn-outline bg-base-200 btn-circle' do %>
            <%= svg_icon('rotate', class: 'w-4 h-4 enabled') %>
            <%= svg_icon('loader', class: 'w-4 h-4 animate-spin disabled') %>
          <% end %>
        </span>
      <% elsif can?(:update, template) %>
        <span class="tooltip tooltip-left" data-tip="<%= t('edit') %>">
          <a href="<%= edit_template_path(template) %>" class="btn btn-xs hover:btn-outline bg-base-200 btn-circle">
            <%= svg_icon('pencil', class: 'w-4 h-4') %>
          </a>
        </span>
      <% end %>
      <% if can?(:create, template) %>
        <span class="tooltip tooltip-left" data-tip="<%= t('clone') %>">
          <a href="<%= new_template_path(base_template_id: template.id) %>" data-turbo-frame="modal" class="btn btn-xs hover:btn-outline bg-base-200 btn-circle">
            <%= svg_icon('copy', class: 'w-4 h-4') %>
          </a>
        </span>
      <% end %>
      <% if can?(:destroy, template) %>
        <span class="tooltip tooltip-left" data-tip="<%= template.archived_at? ? t('delete') : t('archive') %>">
          <%= button_to template_path(template), data: template.archived_at? ? { turbo_confirm: t('template_deletion_is_irreversible_and_will_permanently_remove_all_associated_signed_documents_with_it_are_you_sure_') } : {}, params: { permanently: template.archived_at? }.compact_blank, method: :delete, class: 'btn btn-xs hover:btn-outline bg-base-200 btn-circle', aria_label: t('restore') do %>
            <%= svg_icon(template.archived_at? ? 'trash' : 'archive', class: 'w-4 h-4 enabled') %>
            <%= svg_icon('loader', class: 'w-4 h-4 animate-spin disabled') %>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

docuseal_src/app/views/templates/_title.html.erb
<div class="flex flex-col items-start md:flex-row space-y-2 md:space-y-0 md:space-x-2 md:justify-between md:items-start mb-6 md:mb-3">
  <div class="relative flex items-start justify-between w-full space-x-0">
    <div>
      <h1 class="text-3xl md:text-4xl font-semibold" style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2;">
        <% template.name.split(/(_)/).each do |item| %><%= item %><wbr><% end %>
        <% if template.archived_at? %>
          <span class="ml-1 badge badge-outline badge-lg align-middle"><%= t('archived') %></span>
        <% end %>
      </h1>
      <% if @template.account_id == current_account.id %>
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <a href="<%= folder_path(@template.folder) %>" class="flex items-center space-x-1 mt-1 peer">
              <%= svg_icon('folder', class: 'w-5 h-5 flex-shrink-0') %>
              <span class="text-sm">
                <%= @template.folder.name %>
              </span>
            </a>
            <% if can?(:update, template) %>
              <span class="pl-1 tooltip tooltip-right md:opacity-0 hover:opacity-100 peer-hover:opacity-100" data-tip="<%= t('move') %>">
                <a href="<%= edit_template_folder_path(template.id) %>" data-turbo-frame="modal">
                  <%= svg_icon('pencil_share', class: 'w-5 h-5') %>
                </a>
              </span>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <div class="flex items-center space-x-1 mt-1 peer">
              <span class="badge badge-neutral badge-outline badge-md text-xs text-white uppercase"><%= t('shared') %></span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if !template.archived_at? %>
      <div class="flex items-center space-x-2">
        <% if can?(:update, template) %>
          <div class="tooltip" data-tip="<%= t('preferences') %>">
            <%= link_to template_preferences_path(template), class: 'btn border border-base-200 bg-base-200 hover:bg-base-300 hover:border-base-300 btn-sm flex-1 hidden md:flex', data: { turbo_frame: :modal } do %>
              <span class="flex items-center justify-center space-x-2">
                <%= svg_icon('adjustments_horizontal', class: 'w-6 h-6') %>
              </span>
            <% end %>
          </div>
        <% end %>
        <%= render 'shared/clipboard_copy', text: start_form_url(slug: @template.slug), class: 'absolute md:relative bottom-0 right-0 btn btn-xs md:btn-sm whitespace-nowrap btn-neutral text-white mt-1 px-2', icon_class: 'w-4 h-4 md:w-6 md:h-6 text-white', copy_title: t('link'), copied_title: t('copied'), copy_title_md: t('link'), copied_title_md: t('copied') %>
      </div>
    <% end %>
  </div>
  <div class="flex flex-wrap gap-2 w-full md:w-fit md:justify-between md:flex-none md:pt-1">
    <% if !template.archived_at? && can?(:destroy, template) %>
      <%= button_to button_title(title: t('archive'), disabled_with: t('archiving'), title_class: 'inline', icon: svg_icon('archive', class: 'w-6 h-6')), template_path(template), class: 'btn btn-outline btn-sm w-full', form_class: 'flex-1', method: :delete, data: { turbo_confirm: t('are_you_sure_') } %>
    <% end %>
    <% if can?(:create, current_account.templates.new(author: current_user)) %>
      <%= link_to new_template_path(base_template_id: template.id), class: 'btn btn-outline btn-sm flex-1', data: { turbo_frame: :modal } do %>
        <span class="flex items-center justify-center space-x-2">
          <%= svg_icon('copy', class: 'w-6 h-6') %>
          <span class="inline"><%= t('clone') %></span>
        </span>
      <% end %>
    <% end %>
    <% if !template.archived_at? %>
      <% if can?(:update, template) %>
        <%= link_to edit_template_path(template), class: 'btn btn-outline btn-sm flex-1' do %>
          <span class="flex items-center justify-center space-x-2">
            <%= svg_icon('pencil', class: 'w-6 h-6') %>
            <span><%= t('edit') %></span>
          </span>
        <% end %>
      <% elsif can?(:read, template) && !template.archived_at? %>
        <%= link_to template_preview_path(template), class: 'btn btn-outline btn-sm flex-1' do %>
          <span class="flex items-center justify-center space-x-2">
            <%= svg_icon('file_text', class: 'w-6 h-6') %>
            <span><%= t('preview') %></span>
          </span>
        <% end %>
      <% end %>
    <% end %>
    <% if template.archived_at? %>
      <% if can?(:create, template) %>
        <%= button_to button_title(title: t('restore'), disabled_with: t('restoring'), icon: svg_icon('rotate', class: 'w-6 h-6')), template_restore_index_path(template), class: 'btn btn-outline btn-sm flex-1' %>
      <% end %>
      <%= link_to template_preview_path(template), class: 'btn btn-outline btn-sm flex-1' do %>
        <span class="flex items-center justify-center space-x-2">
          <%= svg_icon('file_text', class: 'w-6 h-6') %>
          <span><%= t('preview') %></span>
        </span>
      <% end %>
    <% end %>
  </div>
</div>

docuseal_src/app/views/templates/_upload_button.html.erb
<%= form_for '', url: templates_upload_path, id: form_id = SecureRandom.uuid, method: :post, class: 'inline', html: { enctype: 'multipart/form-data' } do %>
  <button type="submit" class="btn btn-ghost text-base" onclick="[event.preventDefault(), window.upload_template.click()]">
    <span class="enabled">
      <span class="flex items-center justify-center space-x-2">
        <%= svg_icon('upload', class: 'w-6 h-6 stroke-2') %>
        <span class="hidden md:block"><%= t('upload') %></span>
      </span>
    </span>
    <span class="disabled">
      <span class="flex items-center justify-center space-x-2">
        <%= local_assigns[:icon_disabled] || svg_icon('loader', class: 'w-5 h-5 animate-spin') %>
        <span class="hidden md:block"><%= t('uploading') %>...</span>
      </span>
    </span>
  </button>
  <input type="hidden" name="form_id" value="<%= form_id %>">
  <input id="upload_template" name="files[]" class="hidden" onchange="this.form.requestSubmit()" type="file" accept="image/*, application/pdf<%= ', .docx, .doc, .xlsx, .xls, .odt, .rtf' if Docuseal.multitenant? %>" multiple>
  <input hidden name="folder_name" value="<%= local_assigns[:folder_name] %>">
<% end %>

docuseal_src/app/views/templates/edit.html.erb
<template-builder class="grid" data-template="<%= @template_data %>" data-with-sign-yourself-button="<%= !@template.archived_at? %>" data-with-send-button="<%= !@template.archived_at? && can?(:create, @template.submissions.new(account: current_account)) %>" data-locale="<%= I18n.locale %>"></template-builder>

docuseal_src/app/views/templates/new.html.erb
<%= render 'shared/turbo_modal', title: @base_template ? t('clone_template') : t('new_document_template') do %>
  <%= form_for @template, data: { turbo_frame: :_top }, html: { autocomplete: :off } do |f| %>
    <% if @base_template %>
      <%= hidden_field_tag :base_template_id, @base_template.id %>
    <% end %>
    <% if @base_template && (can?(:manage, :tenants) || true_user != current_user) && true_user.account.linked_accounts.active.accessible_by(current_ability).exists? %>
      <div class="form-control -mb-2 mt-2">
        <%= select_tag :account_id, options_for_select([true_user.account, *true_user.account.linked_accounts.active.accessible_by(current_ability)].uniq.map { |e| [e.name, e.id] }, current_account.id), required: true, class: 'base-select' %>
      </div>
    <% end %>
    <div class="form-control mt-6">
      <%= f.text_field :name, required: true, placeholder: t('document_name'), class: 'base-input', dir: 'auto' %>
    </div>
    <div class="mt-3 mb-4 flex items-center justify-between">
      <a href="#" onclick="[event.preventDefault(), window.folder_name.focus()]">
        <%= svg_icon('folder', class: 'w-6 h-6') %>
      </a>
      <folder-autocomplete class="flex justify-between w-full">
        <input id="folder_name" placeholder="<%= t('folder_name') %>" type="text" class="w-full outline-none border-transparent focus:border-transparent focus:ring-0 bg-base-100 px-1 peer" name="folder_name" value="<%= params[:folder_name].presence || @base_template&.folder&.name || TemplateFolder::DEFAULT_NAME %>" onblur="window.folder_name.value = window.folder_name.value || 'Default'" autocomplete="off">
        <a href="#" onclick="[event.preventDefault(), window.folder_name.value = '', window.folder_name.focus()]" class="shrink-0 link peer-focus:hidden mr-1.5">
          <%= t('change_folder') %>
        </a>
      </folder-autocomplete>
    </div>
    <div class="form-control">
      <%= f.button button_title(title: @base_template ? t('submit') : t('create'), disabled_with: t('creating')), class: 'base-button' %>
    </div>
  <% end %>
<% end %>

docuseal_src/app/views/templates/show.html.erb
<%= render 'title', template: @template %>
<% is_show_tabs = @pagy.pages > 1 || params[:status].present? %>
<% if !@pagy.count.zero? || params[:q].present? || params[:status].present? %>
  <div class="<%= is_show_tabs ? 'mb-4' : 'mb-6' %>">
    <div class="flex justify-between items-center md:items-end">
      <div>
        <h2 class="text-3xl font-bold md:block <%= 'hidden' if params[:q].present? %>">
          <%= t('submissions') %>
        </h2>
      </div>
      <div class="flex justify-end space-x-2">
        <% if params[:q].present? || params[:status].present? || @pagy.pages > 1 %>
          <%= render 'shared/search_input', title_selector: 'h2' %>
        <% end %>
        <%= link_to new_template_submissions_export_path(@template), class: 'hidden md:flex btn btn-ghost text-base', data: { turbo_frame: 'modal' } do %>
          <%= svg_icon('download', class: 'w-6 h-6 stroke-2') %>
          <span><%= t('export') %></span>
        <% end %>
        <% if !@template.archived_at? && can?(:create, Submission) %>
          <%= link_to new_template_submission_path(@template), class: 'white-button !border', data: { turbo_frame: 'modal' } do %>
            <%= svg_icon('plus', class: 'w-6 h-6 stroke-2') %>
            <%= t('add_recipients_html') %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<% if is_show_tabs %>
  <div class="flex items-center md:items-end flex-col space-y-2 md:space-y-0 md:flex-row md:space-x-2 mb-4">
    <a href="<%= url_for(params.to_unsafe_h.except(:status)) %>" class="<%= params[:status].blank? ? 'border-neutral-700' : 'border-neutral-300' %> flex h-10 px-2 py-1 text-lg items-center justify-between border text-center text-neutral font-semibold rounded-xl w-full md:w-48 hover:border-neutral-600">
      <div class="flex items-center space-x-1">
        <%= svg_icon('list', class: 'w-5 h-5') %>
        <span class="font-normal"><%= t('all') %></span>
      </div>
      <div class="badge badge-neutral badge-outline font-medium">
        <%= params[:status].blank? ? @pagy.count : @base_submissions.count %>
      </div>
    </a>
    <a href="<%= url_for(params.to_unsafe_h.merge(status: :pending)) %>" class="<%= params[:status] == 'pending' ? 'border-neutral-700' : 'border-neutral-300' %> flex h-10 px-2 py-1 text-lg items-center justify-between border text-center text-neutral font-semibold rounded-xl w-full md:w-48 hover:border-neutral-600">
      <div class="flex items-center space-x-1">
        <%= svg_icon('clock', class: 'w-5 h-5') %>
        <span class="font-normal"><%= t('pending') %></span>
      </div>
      <div class="badge badge-neutral badge-outline font-medium">
        <%= params[:status] == 'pending' ? @pagy.count : @base_submissions.pending.count %>
      </div>
    </a>
    <a href="<%= url_for(params.to_unsafe_h.merge(status: :completed)) %>" class="<%= params[:status] == 'completed' ? 'border-neutral-700' : 'border-neutral-300' %> flex h-10 px-2 py-1 text-lg items-center justify-between border text-center text-neutral font-semibold rounded-xl w-full md:w-48 hover:border-neutral-600">
      <div class="flex items-center space-x-1">
        <%= svg_icon('circle_check', class: 'w-5 h-5') %>
        <span class="font-normal"><%= t('completed') %></span>
      </div>
      <div class="badge badge-neutral badge-outline font-medium">
        <%= params[:status] == 'completed' ? @pagy.count : @base_submissions.completed.count %>
      </div>
    </a>
  </div>
<% end %>
<% if @submissions.present? %>
  <div class="space-y-4">
    <%= render partial: 'submission', collection: @submissions, locals: { template: @template } %>
  </div>
<% else %>
  <div class="card bg-base-200">
    <div class="card-body text-center px-4 py-16">
      <div class="max-w-lg mx-auto">
        <p class="text-3xl font-bold text-base-content mb-4">
          <%= t('there_are_no_submissions') %>
        </p>
        <% if @template.archived_at.blank? && params[:q].blank? %>
          <p><%= t('send_an_invitation_to_fill_and_complete_the_form') %></p>
          <div class="space-y-2 flex flex-col">
            <% if can?(:create, Submission) %>
              <%= link_to new_template_submission_path(@template, with_link: true), class: 'base-button mt-6', data: { turbo_frame: 'modal' } do %>
                <%= svg_icon('plus', class: 'w-6 h-6 stroke-2') %>
                <span class="mr-1"><%= t('send_to_recipients') %></span>
              <% end %>
            <% end %>
            <% if @template.submitters.size == 1 %>
              <%= link_to start_form_url(slug: @template.slug), class: 'white-button mt-6', target: '_blank', rel: 'noopener' do %>
                <%= svg_icon('writing', class: 'w-6 h-6') %>
                <span class="mr-1"><%= t('sign_it_yourself') %></span>
              <% end %>
            <% else %>
              <%= link_to new_template_submission_path(@template, selfsign: true), class: 'white-button mt-6', data: { turbo_frame: 'modal' } do %>
                <%= svg_icon('writing', class: 'w-6 h-6') %>
                <span class="mr-1"><%= t('sign_it_yourself') %></span>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% view_archived_html = capture do %>
  <% if @template.submissions.where.not(archived_at: nil).exists? && !@template.archived_at? %>
    <div>
      <a href="<%= template_archived_index_path(@template) %>" class="link text-sm"><%= t('view_archived') %></a>
    </div>
  <% end %>
<% end %>
<% if @pagy.pages > 1 %>
  <%= render 'shared/pagination', pagy: @pagy, items_name: 'submissions', left_additional_html: view_archived_html %>
<% else %>
  <div class="mt-2">
    <%= view_archived_html %>
  </div>
<% end %>